#!/usr/bin/env bash

echo "Starting Node $NODE_NUMBER..."

NODE_NUMBER=$NODE_NUMBER NODE_0_IP=$NODE_0_IP NODE_1_IP=$NODE_1_IP NODE_2_IP=$NODE_2_IP TOTAL_NODES=$TOTAL_NODES FAISS_INDEX_PATH=$FAISS_INDEX_PATH DOCUMENTS_DIR=$DOCUMENTS_DIR python -m distributed.run_node